version: '3.8'

services:
  web:
    build:
      context: .
      target: base
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      BUNDLE_DEPLOYMENT: "1"
      BUNDLE_PATH: "/usr/local/bundle"
      BUNDLE_WITHOUT: "production"
    volumes:
      - .:/rails
    depends_on:
      - db
    # Ensure the Rails server is running
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
