default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: city_finder_development

test:
  <<: *default
  database: city_finder_test

production:
  <<: *default
  database: city_finder_production

