default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: city_finder_development

test:
  <<: *default
  database: city_finder_test

production:
  <<: *default
  database: city_finder_production
  username: city_finder
  password: <%= ENV['CITY_FINDER_DATABASE_PASSWORD'] %>
