puts 'Seeding...'

state_sc = State.create(name: 'Santa Catarina')
state_pr = State.create(name: 'Paraná')
state_rs = State.create(name: 'Rio Grande do Sul')

City.create(name: 'Joinville', state: state_sc, state_acronym: 'SC')
City.create(name: 'Blumenau', state: state_sc, state_acronym: 'SC')
City.create(name: 'Itajaí', state: state_sc, state_acronym: 'SC')
City.create(name: 'Criciúma', state: state_sc, state_acronym: 'SC')
City.create(name: 'Chapecó', state: state_sc, state_acronym: 'SC')
City.create(name: 'Jaraguá do Sul', state: state_sc, state_acronym: 'SC')
City.create(name: 'Brusque', state: state_sc, state_acronym: 'SC')
City.create(name: 'Florianópolis', state: state_sc, state_acronym: 'SC')
City.create(name: 'São Bento do Sul', state: state_sc, state_acronym: 'SC')
City.create(name: 'Lages', state: state_sc, state_acronym: 'SC')

City.create(name: 'Maringá', state: state_pr, state_acronym: 'PR')
City.create(name: 'Ponta Grossa', state: state_pr, state_acronym: 'PR')
City.create(name: 'Foz do Iguaçu', state: state_pr, state_acronym: 'PR')
City.create(name: 'Cascavel', state: state_pr, state_acronym: 'PR')
City.create(name: 'São José dos Pinhais', state: state_pr, state_acronym: 'PR')
City.create(name: 'Colombo', state: state_pr, state_acronym: 'PR')
City.create(name: 'Guarapuava', state: state_pr, state_acronym: 'PR')
City.create(name: 'Londrina', state: state_pr, state_acronym: 'PR')
City.create(name: 'Toledo', state: state_pr, state_acronym: 'PR')
City.create(name: 'Paranaguá', state: state_pr, state_acronym: 'PR')

City.create(name: 'Caxias do Sul', state: state_rs, state_acronym: 'RS')
City.create(name: 'Santa Cruz do Sul', state: state_rs, state_acronym: 'RS')
City.create(name: 'Passo Fundo', state: state_rs, state_acronym: 'RS')
City.create(name: 'Novo Hamburgo', state: state_rs, state_acronym: 'RS')
City.create(name: 'São Leopoldo', state: state_rs, state_acronym: 'RS')
City.create(name: 'Bento Gonçalves', state: state_rs, state_acronym: 'RS')
City.create(name: 'Uruguaiana', state: state_rs, state_acronym: 'RS')
City.create(name: 'Porto Alegre', state: state_rs, state_acronym: 'RS')
City.create(name: 'Pelotas', state: state_rs, state_acronym: 'RS')
City.create(name: 'Santa Maria', state: state_rs, state_acronym: 'RS')

puts 'Seeding complete!'
